### ISSUE TITLE
*Testing* Did I delete the folder? 

### ISSUE THREAD

**Issue by Vildelha** [JamesDMSpeed/AfricanBioServices-Vegetation-and-soils#1]
I wanted to update my version of the data, so I first deleted the previous file - now it seems like I deleted the folder "Ecosystem Carbon"/ I cant find it any more. Maybe you could make me a new one James?

**Comment by JamesDMSpeed** [comment]
Reestablished this folder. Empty folders are removed... 
There is probably a more efficient way of reverting the commit that deleted it, but I haven't found that yet.
